# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  pull_request:
    branches: [ "master", "dev" ]
    paths:
      - backend/**

permissions:
  contents: read

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.10
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    - name: Install dependencies
      run: |
        cd backend
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: download ML model
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "BryanEgbert/sentiment140_ml"
        latest: true
        fileName: "*.joblib"
        tarBall: false
        zipBall: false
        out-file-path: backend/
    - name: Test with pytest
      run: |
        cd backend
        pytest
